# -*- coding: utf-8 -*-
"""parkingslotdetection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fGBG1lY9FLDdi4e-dGaAhU1goW3sXAa0
"""

import os
import yaml
import shutil
from ultralytics import YOLO
from google.colab import drive

drive.mount('/content/drive')

DATASET_DIR = "/content/drive/MyDrive/carparkingslotdataset"
DATA_YAML = "/content/drive/MyDrive/carparkingslotdataset/data.yaml"

print("Dataset folder:", DATASET_DIR)
print("Data YAML:", DATA_YAML)

print("Dataset folder exists:", os.path.exists(DATASET_DIR))
print("data.yaml exists:", os.path.exists(DATA_YAML))

folders_to_check = [
    "train/images",
    "train/labels",
    "valid/images",
    "valid/labels",
    "test/images",
    "test/labels"
]

for folder in folders_to_check:
    path = os.path.join(DATASET_DIR, folder)
    if os.path.exists(path):
        print(folder, ":", len(os.listdir(path)), "files")
    else:
        print(folder, ": MISSING")

with open(DATA_YAML, "r") as f:
    data_config = yaml.safe_load(f)

print("Original data.yaml:")
print(data_config)

data_config["path"] = DATASET_DIR
data_config["train"] = "train/images"
data_config["val"] = "valid/images"
data_config["test"] = "test/images"

with open(DATA_YAML, "w") as f:
    yaml.dump(data_config, f)

print("Fixed data.yaml:")
print(data_config)

RESULTS_DIR = "/content/drive/MyDrive/carparkingslotdataset/results"
os.makedirs(RESULTS_DIR, exist_ok=True)

model = YOLO("yolov8n.pt")

results = model.train(
    data=DATA_YAML,
    epochs=50,
    imgsz=640,
    batch=16,
    project=RESULTS_DIR,
    name="parking_slot_yolov8",
    patience=10,
    device=0
)

BEST_MODEL_PATH = "/content/drive/MyDrive/carparkingslotdataset/results/parking_slot_yolov8/weights/best.pt"

best_model = YOLO(BEST_MODEL_PATH)

print("Best model loaded from:")
print(BEST_MODEL_PATH)

metrics = best_model.val(data=DATA_YAML)
print(metrics)

TEST_IMAGES = "/content/drive/MyDrive/carparkingslotdataset/test/images"

predictions = best_model.predict(
    source=TEST_IMAGES,
    conf=0.25,
    save=True,
    project=RESULTS_DIR,
    name="test_predictions"
)

print("Predictions saved to:")
print("/content/drive/MyDrive/carparkingslotdataset/results/test_predictions")

MODEL_SAVE_DIR = "/content/drive/MyDrive/carparkingslotdataset/models"
os.makedirs(MODEL_SAVE_DIR, exist_ok=True)

FINAL_MODEL_PATH = "/content/drive/MyDrive/carparkingslotdataset/models/best_parking_slot_model.pt"

shutil.copy(BEST_MODEL_PATH, FINAL_MODEL_PATH)

print("Final model saved to:")
print(FINAL_MODEL_PATH)

import matplotlib.pyplot as plt
import cv2
import random

PREDICTION_DIR = "/content/drive/MyDrive/carparkingslotdataset/results/test_predictions"

prediction_images = [
    img for img in os.listdir(PREDICTION_DIR)
    if img.lower().endswith((".jpg", ".jpeg", ".png"))

]

plt.figure(figsize=(12, 8))

for i in range(min(6, len(prediction_images))):
    img_path = os.path.join(PREDICTION_DIR, random.choice(prediction_images))
    img = cv2.imread(img_path)
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

    plt.subplot(2, 3, i + 1)
    plt.imshow(img)
    plt.axis("off")

plt.show()

predictions = best_model.predict(
    source="/content/drive/MyDrive/carparkingslotdataset/test/images",
    conf=0.25,
    save=True,
    show_labels=False,
    show_conf=True,
    project="/content/drive/MyDrive/carparkingslotdataset/results",
    name="clean_predictions"
)

VIDEO_PATH = "/content/drive/MyDrive/carparkingslotdataset/videos/parking_test_video.mp4"

video_results = best_model.predict(
    source=VIDEO_PATH,
    conf=0.25,
    save=True,
    project="/content/drive/MyDrive/carparkingslotdataset/results",
    name="video_predictions"
)

print("Video prediction saved to:")
print("/content/drive/MyDrive/carparkingslotdataset/results/video_predictions")

AVI_PATH = "/content/drive/MyDrive/carparkingslotdataset/results/video_predictions/parking_test_video.avi"
MP4_PATH = "/content/drive/MyDrive/carparkingslotdataset/results/video_predictions/parking_test_video.mp4"

!ffmpeg -y -i "{AVI_PATH}" -vcodec libx264 -acodec aac "{MP4_PATH}"

print("Converted MP4 saved to:")
print(MP4_PATH)

import cv2
import os
from ultralytics import YOLO

# Input video
VIDEO_PATH = "/content/drive/MyDrive/carparkingslotdataset/videos/parking_test_video.mp4"

# Save output in the same results folder
RESULTS_DIR = "/content/drive/MyDrive/carparkingslotdataset/results/video_predictions"
os.makedirs(RESULTS_DIR, exist_ok=True)

# Output video path
OUTPUT_PATH = os.path.join(RESULTS_DIR, "parking_test_video_red_green.mp4")

# Load your trained model
BEST_MODEL_PATH = "/content/drive/MyDrive/carparkingslotdataset/results/parking_slot_yolov8/weights/best.pt"
best_model = YOLO(BEST_MODEL_PATH)

print("Model classes:")
print(best_model.names)

# CHANGE THESE BASED ON YOUR RESULTS
# Red = occupied / has car
OCCUPIED_CLASS_IDS = [3, 4, 5]

# Green = empty / open space
EMPTY_CLASS_IDS = [0, 1, 2]

# Open video
cap = cv2.VideoCapture(VIDEO_PATH)

if not cap.isOpened():
    raise FileNotFoundError("Video could not be opened. Check VIDEO_PATH.")

# Get video properties
fps = int(cap.get(cv2.CAP_PROP_FPS))
if fps == 0:
    fps = 25

width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

# Save as MP4
fourcc = cv2.VideoWriter_fourcc(*"mp4v")
out = cv2.VideoWriter(OUTPUT_PATH, fourcc, fps, (width, height))

while True:
    ret, frame = cap.read()

    if not ret:
        break

    # Run YOLO detection
    results = best_model(frame, conf=0.25)

    for result in results:
        boxes = result.boxes

        for box in boxes:
            # Coordinates
            x1, y1, x2, y2 = map(int, box.xyxy[0])

            # Class ID
            cls_id = int(box.cls[0])

            # Confidence score only
            confidence = float(box.conf[0])
            confidence_text = f"{confidence:.2f}"

            # Red for occupied, green for empty
            if cls_id in OCCUPIED_CLASS_IDS:
                color = (0, 0, 255)   # red
            elif cls_id in EMPTY_CLASS_IDS:
                color = (0, 255, 0)   # green
            else:
                color = (255, 255, 255)  # white if unknown

            # Draw bounding box
            cv2.rectangle(frame, (x1, y1), (x2, y2), color, 2)

            # Draw confidence score only
            cv2.putText(
                frame,
                confidence_text,
                (x1, max(y1 - 8, 20)),
                cv2.FONT_HERSHEY_SIMPLEX,
                0.6,
                color,
                2
            )

    out.write(frame)

cap.release()
out.release()

print("Video saved to:")
print(OUTPUT_PATH)

print(best_model.names)

import yaml

DATA_YAML = "/content/drive/MyDrive/carparkingslotdataset/data.yaml"

with open(DATA_YAML, "r") as f:
    data_config = yaml.safe_load(f)

data_config["path"] = "/content/drive/MyDrive/carparkingslotdataset"
data_config["train"] = "train/images"
data_config["val"] = "valid/images"
data_config["test"] = "test/images"

# Keep nc = 6 because your label files already use class IDs 0-5
data_config["nc"] = 6

# Replace broken Roboflow names with clean names
data_config["names"] = [
    "slot",
    "slot",
    "slot",
    "slot",
    "slot",
    "slot"
]

with open(DATA_YAML, "w") as f:
    yaml.dump(data_config, f)

print("Fixed data.yaml:")
print(data_config)

from ultralytics import YOLO
import os

RESULTS_DIR = "/content/drive/MyDrive/carparkingslotdataset/results"
os.makedirs(RESULTS_DIR, exist_ok=True)

model = YOLO("yolov8n.pt")

results = model.train(
    data=DATA_YAML,
    epochs=50,
    imgsz=640,
    batch=16,
    project=RESULTS_DIR,
    name="parking_slot_yolov8_fixed_names",
    patience=10,
    device=0
)